- hosts: 10.182.0.4
  become: true
  tasks:

  - name: transfer package to tmp folder
    copy:
      src: '~/.ssh/ansible-tutorial/ansible.zip'
      dest: '/tmp'

  - name: unzip package
    ansible.builtin.unarchive:
      src: /tmp/ansible.zip
      dest: /tmp
      remote_src: yes

  - name: chmod 777
    ansible.builtin.file:
      path: /tmp/ansible.cfg
      mode: '0777'
