- hosts: 10.182.0.4
  become: true
  vars_prompt:

  - name: filename
    prompt: What is the filename to be transferred (without extension)?
    private: no

  tasks:

  - name: transfer package to tmp folder
    copy:
      src: "~/.ssh/ansible-tutorial/{{ filename }}.zip"
      dest: '/tmp'

  - name: unzip package
    ansible.builtin.unarchive:
      src: "/tmp/{{ filename }}.zip"
      dest: /tmp
      remote_src: yes

  - name: chmod 777
    file:
      path: "/tmp/{{ filename }}"
      mode: '0777'
      recurse: yes
